"""LunarTech AI v7 — i18n (TR/EN) — Level 3 AI Features"""

LANG = {
    "tr": {
        "nav": "🧭 navigation",
        "chat": "💬 Chat",
        "handbook": "📚 Handbook",
        "dashboard": "📊 Dashboard",
        "kg": "� Knowledge Graph",
        "shadow_agents": "🕒 Shadow Agents",
        "swarm_studio": "🧩 Swarm Studio",
        "nav_admin": "🛡️ Admin",
        "model_section": "🤖 model",
        "upload_section": "📄 upload pdf",
        "docs_section": "📚 documents",
        "settings_section": "⚙️ advanced settings",
        "chat_mgmt": "💬 chat management",
        "stats_section": "📊 quick stats",
        "system_section": "🔌 system status",
        "clear": "🗑️ Clear",
        "export": "💾 Export",
        "new_chat": "➕ New Chat",
        "temperature": "🌡️ Temperature",
        "max_tokens": "📏 Max Tokens",
        "rag_mode": "🔍 RAG Mode",
        "system_prompt": "📝 System Prompt",
        "streaming": "⚡ Streaming",
        "favorite": "⭐ Favorite",
        "auto_rag": "🎯 Smart RAG",
        "welcome_title": "👋 Welcome to LunarTech AI",
        "welcome_desc": "Upload your PDF documents, chat with AI, and generate 20,000-word handbooks.",
        "chat_title": "💬 Chat with PDF",
        "chat_input": "Type your question... 💭",
        "followup_title": "💡 Related Questions",
        "smart_mode_label": "Smart mode:",
        "confidence_label": "Confidence",
        "confidence_high": "High",
        "confidence_mid": "Medium",
        "confidence_low": "Low",
        "handbook_title": "📚 Handbook Generator",
        "handbook_desc": "Generate structured handbooks with AgentWrite",
        "handbook_topic": "📝 Topic",
        "handbook_topic_ph": "E.g.: Natural Language Processing with AI Guide",
        "handbook_words": "🎯 Words",
        "handbook_btn": "🚀 Generate Handbook",
        "handbook_need_pdf": "Upload a PDF first to generate a handbook",
        "handbook_format": "📄 Format",
        "format_handbook": "📖 Handbook",
        "format_academic": "🎓 Academic Paper",
        "format_presentation": "📊 Presentation Notes",
        "format_blog": "✍️ Blog Post",
        "dash_title": "📊 Dashboard",
        "dash_desc": "System statistics and activity summary",
        "kg_title": "🔬 Knowledge Graph",
        "kg_desc": "Explore the knowledge network extracted from documents",
        "kg_no_doc": "Upload a PDF first to view the Knowledge Graph.",
        "kg_search": "🔍 Search Entity",
        "docs_label": "Documents",
        "words_label": "Words",
        "queries_label": "Queries",
        "handbooks_label": "Handbooks",
        "sections_label": "Sections",
        "entity_label": "Entities",
        "relation_label": "Relations",
        "density_label": "Density",
        "active": "Active",
        "waiting": "Waiting",
        "connected": "Connected",
        "api_missing": "API Missing",
        "preview": "📖 Preview",
        "messages": "messages",
        "upload_feat": "Drag & drop documents",
        "kg_feat": "Auto entity extraction",
        "chat_feat": "RAG-powered answers",
        "hb_feat": "20K word handbook",
        "error_prefix": "❌ Error",
        "no_text": "Could not extract text!",
        "plan_creating": "📋 Creating writing plan...",
        "context_gathering": "🔍 Gathering context from documents...",
        "total_summary": "Total",
        "page_short": "p",
        "chunk_short": "c",
        "word_short": "w",
        "delete_doc": "Delete",
        "no_doc_yet": "No documents uploaded yet",
        "no_handbook_yet": "No handbooks generated yet",
        "last_messages": "💬 Recent Messages",
        "doc_list": "📄 Documents",
        "handbook_history": "📚 Handbook History",
        "network_view": "🕸️ Network View",
        "custom_prompt_ph": "Write a custom system prompt...",
        "conv_label": "Chat",
        "ai_tools": "🧠 AI Tools",
        "tools": "🛠️ tools",
        "auto_summary": "📝 Summary",
        "key_findings": "🔑 Findings",
        "quiz_generator": "📝 Quiz",
        "doc_compare": "🔄 Compare",
        "research_agent": "🔬 Research",
        "critic_agent": "📋 Critique",
        "translator_agent": "🌍 Translate",
        "auto_tagging": "🏷️ Tags",
        "summary_result": "📝 Document Summary",
        "findings_result": "🔑 Key Findings",
        "quiz_result": "📝 Quiz Questions",
        "compare_result": "🔄 Comparison Report",
        "research_result": "🔬 Research Report",
        "critic_result": "📋 Critique Report",
        "translate_result": "🌍 Translation Result",
        "quiz_type": "Question Type",
        "quiz_count": "Number of Questions",
        "quiz_diff": "Difficulty",
        "quiz_mc": "Multiple Choice",
        "quiz_open": "Open Ended",
        "quiz_tf": "True/False",
        "diff_easy": "Beginner",
        "diff_medium": "Intermediate",
        "diff_hard": "Advanced",
        "select_doc": "Select Document",
        "select_doc2": "2nd Document",
        "run_btn": "▶️ Run",
        "translate_to": "Target Language",
        "text_to_critique": "Text to Critique",
        "research_question": "Research Question",
        "category": "Category",
        "tags": "Tags",
        "difficulty": "Difficulty",
        "generating": "⏳ Generating...",
        "sub_questions": "Sub Questions",
        "report": "Report",
        "no_doc_selected": "Select a document",
        "mind_map": "🧠 Mind Map",
        "swot": "📊 SWOT",
        "flashcards": "🃏 Flashcards",
        "reading_guide": "📖 Reading Guide",
        "cot_agent": "🔗 Step by Step",
        "fact_check": "✅ Fact Check",
        "content_planner": "📅 Content Plan",
        "templates": "📋 Templates",
        "mind_map_result": "🧠 Mind Map",
        "swot_result": "📊 SWOT Analysis",
        "flashcard_result": "🃏 Flashcards",
        "guide_result": "📖 Reading Guide",
        "cot_result": "🔗 Chain of Thought",
        "factcheck_result": "✅ Fact Check Report",
        "plan_result": "📅 Content Plan",
        "cot_question": "Your Question",
        "claims_text": "Claims to Verify",
        "plan_topic": "Topic",
        "plan_type": "Plan Type",
        "plan_blog": "📝 Blog Series",
        "plan_course": "🎓 Online Course",
        "plan_training": "📚 Training Curriculum",
        "plan_social": "📱 Social Media",
        "flashcard_count": "Card Count",
        "template_select": "Select Template",
        "template_run": "▶️ Apply Template",
        "step_n": "Step",
        "steps_total": "steps",
        "grp_doc_intel": "📄 Document Intelligence",
        "grp_writing": "✍️ Writing Assistant",
        "grp_analysis": "🔍 Analysis & Search",
        "grp_reporting": "📊 Reporting",
        "grp_ux": "🧩 Tools",
        "health_score": "💊 Health Score",
        "sentiment": "💭 Sentiment Analysis",
        "citation_gen": "📎 Citation Generator",
        "code_extract": "💻 Code Extraction",
        "doc_timeline": "📅 Document Timeline",
        "writing_coach": "✍️ Writing Coach",
        "prompt_helper": "🔧 Prompt Assistant",
        "paraphrase": "🔄 Paraphrase",
        "cross_ref": "🔗 Cross Reference",
        "gap_analysis": "🕳️ Gap Analysis",
        "glossary": "📖 Glossary",
        "report_builder": "📝 Report Builder",
        "pres_maker": "🎤 Presentation Maker",
        "email_drafter": "📧 Email Drafter",
        "session_notes": "📒 Session Notes",
        "favorites": "⭐ Favorites",
        "health_result": "💊 Health Report",
        "sentiment_result": "💭 Sentiment Report",
        "citation_result": "📎 Citation Report",
        "code_result": "💻 Code Blocks",
        "timeline_result": "📅 Timeline",
        "coach_result": "✍️ Writing Analysis",
        "prompt_result": "🔧 Prompt Analysis",
        "paraphrase_result": "🔄 Rewritten Text",
        "crossref_result": "🔗 Cross Reference",
        "gap_result": "🕳️ Gap Report",
        "glossary_result": "📖 Glossary",
        "report_result": "📝 Report",
        "pres_result": "🎤 Presentation",
        "email_result": "📧 Email",
        "text_to_coach": "Text to Review",
        "prompt_to_improve": "Prompt to Improve",
        "text_to_paraphrase": "Text to Paraphrase",
        "paraphrase_style": "Writing Style",
        "style_academic": "🎓 Academic",
        "style_simple": "📝 Simple",
        "style_formal": "👔 Formal",
        "style_creative": "🎨 Creative",
        "style_technical": "⚙️ Technical",
        "style_journalistic": "📰 Journalistic",
        "report_type": "Report Type",
        "rpt_analysis": "📊 Analysis",
        "rpt_summary": "📋 Summary",
        "rpt_executive": "👔 Executive",
        "rpt_technical": "⚙️ Technical",
        "rpt_progress": "📈 Progress",
        "slide_count": "Slide Count",
        "email_type": "Email Type",
        "email_summary": "📋 Summary",
        "email_request": "📩 Request",
        "email_followup": "🔄 Follow-up",
        "email_report": "📊 Report",
        "email_announce": "📢 Announcement",
        "add_note": "📝 Add Note",
        "note_text": "Note text...",
        "no_notes": "No notes yet",
        "clear_notes": "🗑️ Clear Notes",
        "export_notes": "💾 Export Notes",
        "no_favorites": "No favorites yet",
        "save_favorite": "⭐ Add to Favorites",
        "fav_saved": "Added to favorites!",
        "clear_favorites": "🗑️ Clear Favorites",
        "readability": "Readability",
        "consistency": "Consistency",
        "completeness": "Completeness",
        "structure": "Structure",
        "clarity": "Clarity",
        "file": "File",
        "login_title": "Sign In",
        "login_desc": "Log in to access LunarTech AI v4 platform.",
        "login_tab": "Sign In",
        "register_tab": "Register",
        "email_label": "Email",
        "password_label": "Password",
        "password_conf_label": "Password (Repeat)",
        "login_btn": "Sign In",
        "register_btn": "Create Account",
        "auth_empty_fields": "Please fill in email and password.",
        "auth_password_mismatch": "Passwords do not match.",
        "login_success": "Login successful! Redirecting...",
        "register_success": "Registration successful! Please sign in.",
        "auth_failed": "Authentication failed.",
        "logout_btn": "Sign Out",
        "total": "Total",
        "formality": "Formality",
        "subjectivity": "Subjectivity",
        "term": "Term",
        "definition": "Definition",
        "tool_category": "Tool Category",
        "table_extract": "📊 Table Extraction",
        "persona_chat": "🎭 AI Persona",
        "multi_analysis": "📚 Bulk Analysis",
        "question_bank": "🏦 Question Bank",
        "doc_diff": "🔀 Document Diff",
        "table_result": "📊 Tables",
        "persona_result": "🎭 Persona Response",
        "multi_result": "📚 Bulk Analysis",
        "qbank_result": "🏦 Question Bank",
        "diff_result": "🔀 Difference Report",
        "persona_select": "Select Persona",
        "persona_teacher": "👨‍🏫 Teacher",
        "persona_lawyer": "⚖️ Lawyer",
        "persona_scientist": "🔬 Scientist",
        "persona_business": "💼 Business Advisor",
        "persona_creative": "🎨 Creative Writer",
        "persona_question": "Your Question",
        "qbank_count": "Question Count",
        "token_usage": "Token Usage",
        "cache_stats": "Cache Stats",
        "copy_result": "📋 Copy",
        "download_result": "💾 Download",
        "auth_user_req": "Please explicitly input your e-mail to continue.",
        "admin_title": "Administration Panel",
        "admin_desc": "Financial metrics & system health reports",
        "admin_unauthorized": "You are unauthorized to view this page.",
    },
    "en": {
        "nav": "🧭 navigation",
        "chat": "💬 Chat",
        "handbook": "📚 Handbook",
        "dashboard": "📊 Dashboard",
        "kg": "🔬 Knowledge Graph",
        "model_section": "🤖 model",
        "upload_section": "📄 upload pdf",
        "docs_section": "📚 documents",
        "settings_section": "⚙️ advanced settings",
        "chat_mgmt": "💬 chat management",
        "stats_section": "📊 quick stats",
        "system_section": "🔌 system status",
        "clear": "🗑️ Clear",
        "export": "💾 Export",
        "new_chat": "➕ New Chat",
        "temperature": "🌡️ Temperature",
        "max_tokens": "📏 Max Tokens",
        "rag_mode": "🔍 RAG Mode",
        "system_prompt": "📝 System Prompt",
        "streaming": "⚡ Streaming",
        "favorite": "⭐ Favorite",
        "auto_rag": "🎯 Smart RAG",
        "welcome_title": "👋 Welcome to LunarTech AI",
        "welcome_desc": "Upload your PDF documents, chat with AI, and generate 20,000-word handbooks.",
        "chat_title": "💬 Chat with PDF",
        "chat_input": "Type your question... 💭",
        "followup_title": "💡 Related Questions",
        "smart_mode_label": "Smart mode:",
        "confidence_label": "Confidence",
        "confidence_high": "High",
        "confidence_mid": "Medium",
        "confidence_low": "Low",
        "handbook_title": "📚 Handbook Generator",
        "handbook_desc": "Generate structured handbooks with AgentWrite",
        "handbook_topic": "📝 Topic",
        "handbook_topic_ph": "E.g.: Natural Language Processing with AI Guide",
        "handbook_words": "🎯 Words",
        "handbook_btn": "🚀 Generate Handbook",
        "handbook_need_pdf": "Upload a PDF first to generate a handbook",
        "handbook_format": "📄 Format",
        "format_handbook": "📖 Handbook",
        "format_academic": "🎓 Academic Paper",
        "format_presentation": "📊 Presentation Notes",
        "format_blog": "✍️ Blog Post",
        "dash_title": "📊 Dashboard",
        "dash_desc": "System statistics and activity summary",
        "kg_title": "🔬 Knowledge Graph",
        "kg_desc": "Explore the knowledge network extracted from documents",
        "kg_no_doc": "Upload a PDF first to view the Knowledge Graph.",
        "kg_search": "🔍 Search Entity",
        "docs_label": "Documents",
        "words_label": "Words",
        "queries_label": "Queries",
        "handbooks_label": "Handbooks",
        "sections_label": "Sections",
        "entity_label": "Entities",
        "relation_label": "Relations",
        "density_label": "Density",
        "active": "Active",
        "waiting": "Waiting",
        "connected": "Connected",
        "api_missing": "API Missing",
        "preview": "📖 Preview",
        "messages": "messages",
        "upload_feat": "Drag & drop documents",
        "kg_feat": "Auto entity extraction",
        "chat_feat": "RAG-powered answers",
        "hb_feat": "20K word handbook",
        "error_prefix": "❌ Error",
        "no_text": "Could not extract text!",
        "plan_creating": "📋 Creating writing plan...",
        "context_gathering": "🔍 Gathering context from documents...",
        "total_summary": "Total",
        "page_short": "p",
        "chunk_short": "c",
        "word_short": "w",
        "delete_doc": "Delete",
        "no_doc_yet": "No documents uploaded yet",
        "no_handbook_yet": "No handbooks generated yet",
        "last_messages": "💬 Recent Messages",
        "doc_list": "📄 Documents",
        "handbook_history": "📚 Handbook History",
        "network_view": "🕸️ Network View",
        "custom_prompt_ph": "Write a custom system prompt...",
        "conv_label": "Chat",
        "ai_tools": "🧠 AI Tools",
        "tools": "🛠️ tools",
        "auto_summary": "📝 Summary",
        "key_findings": "🔑 Findings",
        "quiz_generator": "📝 Quiz",
        "doc_compare": "🔄 Compare",
        "research_agent": "🔬 Research",
        "critic_agent": "📋 Critique",
        "translator_agent": "🌍 Translate",
        "auto_tagging": "🏷️ Tags",
        "summary_result": "📝 Document Summary",
        "findings_result": "🔑 Key Findings",
        "quiz_result": "📝 Quiz Questions",
        "compare_result": "🔄 Comparison Report",
        "research_result": "🔬 Research Report",
        "critic_result": "📋 Critique Report",
        "translate_result": "🌍 Translation Result",
        "quiz_type": "Question Type",
        "quiz_count": "Question Count",
        "quiz_diff": "Difficulty",
        "quiz_mc": "Multiple choice",
        "quiz_open": "Open-ended",
        "quiz_tf": "True/False",
        "diff_easy": "Easy",
        "diff_medium": "Medium",
        "diff_hard": "Hard",
        "select_doc": "Select Document",
        "select_doc2": "2nd Document",
        "run_btn": "▶️ Run",
        "translate_to": "Target Language",
        "text_to_critique": "Text to Critique",
        "research_question": "Research Question",
        "category": "Category",
        "tags": "Tags",
        "difficulty": "Difficulty",
        "generating": "⏳ Generating...",
        "sub_questions": "Sub Questions",
        "report": "Report",
        "no_doc_selected": "Select a document",
        "mind_map": "🧠 Mind Map",
        "swot": "📊 SWOT",
        "flashcards": "🃏 Flashcards",
        "reading_guide": "📖 Reading Guide",
        "cot_agent": "🔗 Step by Step",
        "fact_check": "✅ Fact Check",
        "content_planner": "📅 Content Plan",
        "templates": "📋 Templates",
        "mind_map_result": "🧠 Mind Map",
        "swot_result": "📊 SWOT Analysis",
        "flashcard_result": "🃏 Flashcards",
        "guide_result": "📖 Reading Guide",
        "cot_result": "🔗 Chain of Thought",
        "factcheck_result": "✅ Fact Check Report",
        "plan_result": "📅 Content Plan",
        "cot_question": "Your Question",
        "claims_text": "Claims to Verify",
        "plan_topic": "Topic",
        "plan_type": "Plan Type",
        "plan_blog": "📝 Blog Series",
        "plan_course": "🎓 Online Course",
        "plan_training": "📚 Training Curriculum",
        "plan_social": "📱 Social Media",
        "flashcard_count": "Card Count",
        "template_select": "Select Template",
        "template_run": "▶️ Apply Template",
        "step_n": "Step",
        "steps_total": "steps",
        # Level 3
        "grp_doc_intel": "📄 Document Intelligence",
        "grp_writing": "✍️ Writing Assistant",
        "grp_analysis": "🔍 Analysis & Search",
        "grp_reporting": "📊 Reporting",
        "grp_ux": "🧩 Tools",
        "health_score": "💊 Health Score",
        "sentiment": "💭 Sentiment",
        "citation_gen": "📎 Citation",
        "code_extract": "💻 Code Extract",
        "doc_timeline": "📅 Timeline",
        "writing_coach": "✍️ Writing Coach",
        "prompt_helper": "🔧 Prompt Helper",
        "paraphrase": "🔄 Paraphrase",
        "cross_ref": "🔗 Cross-Reference",
        "gap_analysis": "🕳️ Gap Analysis",
        "glossary": "📖 Glossary",
        "report_builder": "📝 Report Builder",
        "pres_maker": "🎤 Presentation",
        "email_drafter": "📧 Email Draft",
        "session_notes": "📒 Session Notes",
        "favorites": "⭐ Favorites",
        "health_result": "💊 Health Report",
        "sentiment_result": "💭 Sentiment Report",
        "citation_result": "📎 Citations",
        "code_result": "💻 Code Blocks",
        "timeline_result": "📅 Timeline",
        "coach_result": "✍️ Writing Analysis",
        "prompt_result": "🔧 Prompt Analysis",
        "paraphrase_result": "🔄 Paraphrased",
        "crossref_result": "🔗 Cross-References",
        "gap_result": "🕳️ Gap Report",
        "glossary_result": "📖 Glossary",
        "report_result": "📝 Report",
        "pres_result": "🎤 Presentation",
        "email_result": "📧 Email",
        "text_to_coach": "Text to Review",
        "prompt_to_improve": "Prompt to Improve",
        "text_to_paraphrase": "Text to Paraphrase",
        "paraphrase_style": "Writing Style",
        "style_academic": "🎓 Academic",
        "style_simple": "📝 Simple",
        "style_formal": "👔 Formal",
        "style_creative": "🎨 Creative",
        "style_technical": "⚙️ Technical",
        "style_journalistic": "📰 Journalistic",
        "report_type": "Report Type",
        "rpt_analysis": "📊 Analysis",
        "rpt_summary": "📋 Summary",
        "rpt_executive": "👔 Executive",
        "rpt_technical": "⚙️ Technical",
        "rpt_progress": "📈 Progress",
        "slide_count": "Slide Count",
        "email_type": "Email Type",
        "email_summary": "📋 Summary",
        "email_request": "📩 Request",
        "email_followup": "🔄 Follow-up",
        "email_report": "📊 Report",
        "email_announce": "📢 Announcement",
        "add_note": "📝 Add Note",
        "note_text": "Note text...",
        "no_notes": "No notes yet",
        "clear_notes": "🗑️ Clear Notes",
        "export_notes": "💾 Export Notes",
        "no_favorites": "No favorites yet",
        "save_favorite": "⭐ Save to Favorites",
        "fav_saved": "Saved to favorites!",
        "clear_favorites": "🗑️ Clear Favorites",
        "readability": "Readability",
        "consistency": "Consistency",
        "completeness": "Completeness",
        "structure": "Structure",
        "clarity": "Clarity",
        "grade": "Grade",
        "total": "Total",
        "formality": "Formality",
        "subjectivity": "Subjectivity",
        "term": "Term",
        "definition": "Definition",
        "tool_category": "Tool Category",
        # Level 4 AI Features
        "table_extract": "📊 Table Extract",
        "persona_chat": "🎭 AI Persona",
        "multi_analysis": "📚 Multi Analysis",
        "question_bank": "🏦 Question Bank",
        "doc_diff": "🔀 Doc Diff",
        "table_result": "📊 Tables",
        "persona_result": "🎭 Persona Response",
        "multi_result": "📚 Multi Analysis",
        "qbank_result": "🏦 Question Bank",
        "diff_result": "🔀 Diff Report",
        "persona_select": "Select Persona",
        "persona_teacher": "👨‍🏫 Teacher",
        "persona_lawyer": "⚖️ Lawyer",
        "persona_scientist": "🔬 Scientist",
        "persona_business": "💼 Business Advisor",
        "persona_creative": "🎨 Creative Writer",
        "persona_question": "Your Question",
        "qbank_count": "Question Count",
        "token_usage": "Token Usage",
        "cache_stats": "Cache Statistics",
        "copy_result": "📋 Copy",
        "download_result": "💾 Download",
        "auth_user_req": "Please enter only your email address to reset your password.",
        "nav_admin": "Admin Panel",
        "admin_title": "Administration Panel",
        "admin_desc": "Financial statistics and token consumption metrics",
        "admin_unauthorized": "You do not have permission to access this page.",
    },
}
