import re
import io
import pandas as pd
from fpdf import FPDF
from docx import Document


def _strip_markdown(text: str) -> str:
    """Markdown işaretlerini basitçe temizler."""
    text = re.sub(r"\*\*(.*?)\*\*", r"\1", text)
    text = re.sub(r"\*(.*?)\*", r"\1", text)
    text = re.sub(r"#(.*?)\n", r"\1\n", text)
    text = re.sub(r"\[(.*?)\]\(.*?\)", r"\1", text)
    return text.replace("`", "")


def export_pdf(text: str, title: str = "LunarTech AI Raporu") -> bytes:
    """Metni PDF dosyası olarak byte formatında döndürür."""
    pdf = FPDF()
    pdf.add_page()

    # Şık, Kurumsal Başlık
    pdf.set_font("Arial", "B", size=18)
    pdf.set_text_color(99, 102, 241)  # LunarTech Indigo
    pdf.cell(
        200,
        10,
        txt=title.encode("latin-1", "replace").decode("latin-1"),
        ln=True,
        align="C",
    )
    pdf.set_font("Arial", "I", size=10)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(200, 6, txt="Generated by LunarTech AI Enterprise", ln=True, align="C")
    pdf.ln(10)

    pdf.set_font("Arial", size=11)
    pdf.set_text_color(0, 0, 0)
    clean_text = _strip_markdown(text)
    for line in clean_text.split("\n"):
        safe_line = line.encode("latin-1", "replace").decode("latin-1")
        pdf.multi_cell(0, 7, txt=safe_line)

    return pdf.output(dest="S").encode("latin-1", "replace")


def export_docx(text: str, title: str = "LunarTech AI Raporu") -> bytes:
    """Metni Word dokümanı (DOCX) olarak döndürür."""
    doc = Document()

    # Kurumsal Başlık
    heading = doc.add_heading(title, 0)
    heading.alignment = 1  # Center

    subtitle = doc.add_paragraph("Generated by LunarTech AI Enterprise")
    subtitle.alignment = 1

    clean_text = _strip_markdown(text)
    for paragraph in clean_text.split("\n\n"):
        if paragraph.strip():
            doc.add_paragraph(paragraph.strip())

    bio = io.BytesIO()
    doc.save(bio)
    return bio.getvalue()


def extract_tables_to_excel(text: str) -> bytes:
    """Markdown metnindeki tabloları bulup Excel dosyasına çevirir."""
    # Basit Markdown Tablo Bulucu (örn. | Başlık 1 | Başlık 2 |)
    lines = text.split("\n")
    table_rows = []
    in_table = False

    for line in lines:
        if line.strip().startswith("|") and line.strip().endswith("|"):
            if "---" in line:
                continue  # Ayırıcı satırları atla
            row = [cell.strip() for cell in line.strip().split("|")][1:-1]
            if row:
                table_rows.append(row)
                in_table = True
        else:
            if in_table:
                break  # Tablo bitti

    if not table_rows:
        return b""

    df = pd.DataFrame(table_rows[1:], columns=table_rows[0])
    bio = io.BytesIO()
    with pd.ExcelWriter(bio, engine="openpyxl") as writer:
        df.to_excel(writer, index=False, sheet_name="Çıktı")
    return bio.getvalue()
