import os, sys

PROJECT_ROOT = os.path.dirname(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
)
if PROJECT_ROOT not in sys.path:
    sys.path.insert(0, PROJECT_ROOT)
import streamlit as st
import config
from app.lang import LANG


def t(key):
    lang = st.session_state.get("lang", "tr")
    return LANG.get(lang, LANG["tr"]).get(key, key)


from services import handbook_service, lightrag_service
from utils.helpers import count_words
import time


def render_handbook_page():
    st.markdown(
        f'<div class="pg-header"><div class="pg-title pg-title-handbook">{t("handbook_title")}</div><div class="pg-sub">{t("handbook_desc")}</div></div>',
        unsafe_allow_html=True,
    )
    c1, c2, c3 = st.columns([3, 1, 1])
    with c1:
        topic = st.text_input(t("handbook_topic"), placeholder=t("handbook_topic_ph"))
    with c2:
        target_words = st.number_input(
            t("handbook_words"),
            min_value=5000,
            max_value=50000,
            value=config.MAX_HANDBOOK_WORDS,
            step=5000,
        )
    with c3:
        fmt_options = {
            t("format_handbook"): "handbook",
            t("format_academic"): "academic",
            t("format_presentation"): "presentation",
            t("format_blog"): "blog",
        }
        fmt_label = st.selectbox(t("handbook_format"), list(fmt_options.keys()))
        output_format = fmt_options[fmt_label]

    if not st.session_state.has_documents:
        st.markdown(
            f'<div class="empty-state"><div class="empty-icon">📄</div><div class="empty-text">{t("handbook_need_pdf")}</div></div>',
            unsafe_allow_html=True,
        )

    if st.button(
        t("handbook_btn"),
        use_container_width=True,
        disabled=not topic
        or not st.session_state.has_documents
        or st.session_state.get("hb_interactive_state") is not None,
        type="primary",
    ):
        st.session_state.hb_interactive_state = (
            handbook_service.start_interactive_generation(
                topic, st.session_state.selected_model
            )
        )
        st.session_state.hb_pending_draft = None
        st.session_state.hb_custom_instruction = ""
        st.rerun()

    if st.session_state.get("hb_interactive_state"):
        _render_interactive_handbook_flow()
    elif st.session_state.get("handbook_result"):
        _show_handbook(st.session_state.handbook_result)


def _render_interactive_handbook_flow():
    from core.longwriter import (
        generate_handbook_section,
        approve_handbook_section,
        finalize_interactive_handbook,
    )
    from services.handbook_service import (
        rag_query_func_wrapper,
        save_interactive_handbook,
    )

    state = st.session_state.hb_interactive_state

    if state["current_idx"] < len(state["plan"]):
        current_section = state["plan"][state["current_idx"]]

        st.markdown(
            f"### ✍️ Writing Process: Section {state['current_idx']+1} / {len(state['plan'])}"
        )
        st.info(
            f"**Current Section:** {current_section['title']}\n\n*The agent is generating this section or waiting for your approval.*"
        )

        if st.session_state.get("hb_pending_draft") is None:
            with st.spinner("AI is writing the section draft... Please wait."):
                draft = generate_handbook_section(
                    state,
                    st.session_state.get("hb_custom_instruction"),
                    rag_query_func_wrapper,
                )
                st.session_state.hb_pending_draft = draft
                st.session_state.hb_custom_instruction = ""
                st.rerun()

        if st.session_state.get("hb_pending_draft"):
            st.markdown("#### 📝 Draft Review")
            st.markdown(
                "You can manually edit the draft generated by the AI below or instruct the AI to revise it."
            )

            edited_draft = st.text_area(
                "Section Content Editor",
                value=st.session_state.hb_pending_draft,
                height=400,
            )

            c1, c2, c3 = st.columns([3, 4, 3])
            with c1:
                st.markdown("<br>", unsafe_allow_html=True)
                if st.button(
                    "✅ Approve & Proceed to Next Section",
                    type="primary",
                    use_container_width=True,
                ):
                    approve_handbook_section(state, edited_draft)
                    st.session_state.hb_pending_draft = None
                    st.rerun()

            with c2:
                instruction = st.text_input(
                    "Improve Draft (Provide Revision):",
                    key="hb_rev_input",
                    placeholder="E.g.: Use a more technical tone.",
                )

            with c3:
                st.markdown("<br>", unsafe_allow_html=True)
                if st.button("🔄 Rewrite", use_container_width=True):
                    st.session_state.hb_custom_instruction = instruction
                    st.session_state.hb_pending_draft = None
                    st.rerun()

            if st.button("❌ Cancel Process", type="secondary"):
                st.session_state.hb_interactive_state = None
                st.session_state.hb_pending_draft = None
                st.rerun()

    else:
        with st.spinner("Compiling the book..."):
            result = finalize_interactive_handbook(state)

            uid = (
                st.session_state.workspace_id
                if st.session_state.get("workspace_id")
                else (
                    st.session_state.user.id
                    if hasattr(st.session_state.get("user"), "id")
                    else None
                )
            )
            doc_id = st.session_state.current_doc_id

            save_interactive_handbook(result, doc_id, uid)

            st.session_state.handbook_result = result
            st.session_state.handbook_history.append(
                {
                    "title": result["title"],
                    "word_count": result["word_count"],
                    "time": result["generation_time"],
                }
            )
            st.session_state.hb_interactive_state = None
            st.session_state.hb_pending_draft = None
            st.balloons()
            st.rerun()


def _show_handbook(r):
    st.markdown('<hr class="glow-div">', unsafe_allow_html=True)
    cols = st.columns(4)
    m = [
        (f"📝", t("words_label"), f"{r['word_count']:,}"),
        ("📑", t("sections_label"), str(r["section_count"])),
        ("⏱️", "", r["generation_time"]),
        ("🎯", "", f"{min(100,int(r['word_count']/config.MAX_HANDBOOK_WORDS*100))}%"),
    ]
    for col, (ic, lb, vl) in zip(cols, m):
        with col:
            st.markdown(
                f'<div class="m-card"><div class="m-val">{vl}</div><div class="m-lbl">{ic} {lb}</div></div>',
                unsafe_allow_html=True,
            )
    st.markdown("<br>", unsafe_allow_html=True)
    c1, c2, c3 = st.columns(3)
    with c1:
        st.download_button(
            "📥 Markdown",
            data=r["content"],
            file_name=f"handbook.md",
            mime="text/markdown",
            use_container_width=True,
            type="primary",
        )
    with c2:
        st.download_button(
            "📥 Text",
            data=r["content"],
            file_name=f"handbook.txt",
            mime="text/plain",
            use_container_width=True,
        )
    with c3:
        st.download_button(
            "📥 HTML",
            data=_to_html(r["content"], r["title"]),
            file_name=f"handbook.html",
            mime="text/html",
            use_container_width=True,
        )
    with st.expander(t("preview"), expanded=True):
        st.markdown(r["content"])


# ══════════════════════════════════════════════════════════
# PAGE: DASHBOARD
# ══════════════════════════════════════════════════════════
